
services:
  ui-shell:
    build:
      context: ./ui-shell
      dockerfile: Dockerfile  
    ports:
      - "5173:5173"   
    depends_on:
      - matching-ui
      - questions-ui
      - collab-ui
      - user-ui
      - history-ui
    container_name: peerprep-ui-shell
    
  matching-ui:
    build:
      context: ./ui-services/matching-ui-service
      dockerfile: Dockerfile
    ports:
      - "5174:5174"
    container_name: peerprep-matching-ui

  questions-ui:
    build:
      context: ./ui-services/question-ui-service
      dockerfile: Dockerfile
    ports:
      - "5175:5175"
    container_name: peerprep-question-ui

  collab-ui:
    build:
      context: ./ui-services/collab-ui-service
      dockerfile: Dockerfile
    ports:
      - "5176:5176"
    container_name: peerprep-collab-ui

  user-ui:
    build:
      context: ./ui-services/user-ui-service
      dockerfile: Dockerfile
    ports:
      - "5177:5177"
    container_name: peerprep-user-ui
  history-ui:
    build:
      context: ./ui-services/history-ui-service
      dockerfile: Dockerfile
    ports:
      - "5178:5178"
    container_name: peerprep-history-ui
