name: Build & Push Docker images

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master

jobs: 
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service:
          # Add one entry per microservice
          - name: matching-ui
            context: ./ui-services/matching-ui-service
            dockerfile: Dockerfile
          - name: questions-ui
            context: ./ui-services/question-ui-service
            dockerfile: Dockerfile
          - name: collab-ui
            context: ./ui-services/collab-ui-service
            dockerfile: Dockerfile
          - name: user-ui
            context: ./ui-services/user-ui-service
            dockerfile: Dockerfile
          - name: history-ui
            context: ./ui-services/history-ui-service
            dockerfile: Dockerfile

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Force owner to lowercase
        run: echo "REPO_OWNER_LC=$(echo '${{ env.REPO_OWNER_LC }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.REPO_OWNER_LC }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata (tags/labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ env.REPO_OWNER_LC }}/peerprep-${{ matrix.service.name }}
          tags: |
            type=raw,value=${{ github.sha }}
            type=ref,event=branch
            type=ref,event=tag
            type=raw,value=latest,enable=${{ github.ref_name == 'main' || github.ref_name == 'master' }}

      - name: Build (no push for PRs)
        if: ${{ github.event_name == 'pull_request' }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.service.context }}
          file: ${{ matrix.service.dockerfile }}
          push: false
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build & Push
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.service.context }}
          file: ${{ matrix.service.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
        