name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build all services with docker-compose
        run: docker compose build

      - name: Start services
        run: docker compose up -d

      - name: Tear down
        if: always()
        run: docker compose down -v

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push with docker-compose
        run: docker compose build && docker compose push
