name: Run tests and upload coverage

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service:
          # Add one entry per microservice
          - name: leetcode-backend
            context: ./backend-services/leetcode-backend-service

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install
        working-directory: ${{ matrix.service.context }}

        # Step 1: Run Vitest with coverage + JUnit reporter
      - name: Run tests (coverage + JUnit)
        working-directory: ${{ matrix.service.context }}
        run: |
          mkdir -p test-results
          npm vitest run --coverage --reporter=junit --outputFile=./test-results/junit.xml

      # Step 2: Upload test results (JUnit) to Codecov
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          # Point this to where we just wrote the XML (relative to repo root)
          files: ${{ matrix.service.context }}/test-results/junit.xml
          flags: ${{ matrix.service.name }}

      # Step 3: Upload coverage to Codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          # Vitest (c8) writes lcov.info under coverage/ by default
          files: |
            ${{ matrix.service.context }}/coverage/lcov.info
          flags: ${{ matrix.service.name }}
          fail_ci_if_error: true
